/**
 * Keeps packages/validator/schemas/ (the schema documents bundled into the
 * published @ulcs/validator package — see ADR-0006) in sync with the
 * canonical source of truth at repo-root schemas/v1/.
 *
 * Usage:
 *   tsx scripts/sync-validator-schemas.ts          # copy canonical -> bundled
 *   tsx scripts/sync-validator-schemas.ts --check   # verify they already match; exit 1 if not
 *
 * schemas/v1/ remains the single place a human edits a schema (per
 * ADR-0003); packages/validator/schemas/ is a generated, committed mirror,
 * regenerated by this script and verified by --check in CI so drift is
 * caught immediately rather than silently shipping stale bundled schemas.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const sourceDir = path.join(repoRoot, "schemas", "v1");
const targetDir = path.join(repoRoot, "packages", "validator", "schemas", "v1");

function listFilesRecursive(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) {
      found.push(...listFilesRecursive(full));
    } else {
      found.push(full);
    }
  }
  return found;
}

function copy(): void {
  if (existsSync(targetDir)) rmSync(targetDir, { recursive: true, force: true });
  mkdirSync(targetDir, { recursive: true });
  for (const sourceFile of listFilesRecursive(sourceDir)) {
    const relative = path.relative(sourceDir, sourceFile);
    const targetFile = path.join(targetDir, relative);
    mkdirSync(path.dirname(targetFile), { recursive: true });
    writeFileSync(targetFile, readFileSync(sourceFile));
  }
  console.log(
    `Synced ${listFilesRecursive(sourceDir).length} schema file(s) into packages/validator/schemas/v1/`,
  );
}

function check(): boolean {
  if (!existsSync(targetDir)) {
    console.error(
      "packages/validator/schemas/v1/ does not exist. Run: pnpm run sync:validator-schemas",
    );
    return false;
  }
  const sourceFiles = listFilesRecursive(sourceDir)
    .map((f) => path.relative(sourceDir, f))
    .sort();
  const targetFiles = listFilesRecursive(targetDir)
    .map((f) => path.relative(targetDir, f))
    .sort();

  let ok = true;
  if (JSON.stringify(sourceFiles) !== JSON.stringify(targetFiles)) {
    console.error("File sets differ between schemas/v1/ and packages/validator/schemas/v1/:");
    console.error(`  source: ${sourceFiles.join(", ")}`);
    console.error(`  bundled: ${targetFiles.join(", ")}`);
    ok = false;
  }

  for (const relative of sourceFiles) {
    const sourceContent = existsSync(path.join(sourceDir, relative))
      ? readFileSync(path.join(sourceDir, relative), "utf8")
      : undefined;
    const targetPath = path.join(targetDir, relative);
    const targetContent = existsSync(targetPath) ? readFileSync(targetPath, "utf8") : undefined;
    if (sourceContent !== targetContent) {
      console.error(
        `Stale bundled schema: packages/validator/schemas/v1/${relative} does not match schemas/v1/${relative}`,
      );
      ok = false;
    }
  }

  if (ok) {
    console.log(
      `packages/validator/schemas/v1/ is in sync with schemas/v1/ (${sourceFiles.length} file(s)).`,
    );
  } else {
    console.error("\nRun: pnpm run sync:validator-schemas");
  }
  return ok;
}

function main(): void {
  const checkOnly = process.argv.includes("--check");
  if (checkOnly) {
    const ok = check();
    process.exitCode = ok ? 0 : 1;
  } else {
    copy();
  }
}

main();
